### ISSUE TITLE
Use 2605 as Item for CRAFT

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#16]
Using 2605 as Item for CRAFT, thanks to @Tendy-Insane

**Comment by Celebi91** [comment]
Si prega di avere scritto per bene cosa deve fare il sistema maestria e gli effetti dati.
Grazie

**Comment by Celebi91** [comment]
Cosa devo fare qui?

**Comment by Achille-exe** [comment]
Pardon, non ho specificato
Se puoi fare che Raid Laurena e Raid Fafnir diano x2 di questo item a ogni fine raid

**Comment by Celebi91** [comment]
Nel box?

Il Lun 16 Set 2019, 19:43 Achille88 <notifications@github.com> ha scritto:

**Comment by Achille-exe** [comment]
Nono, il raid alla fine deve dare box(già fatta con tutti i vari drop) e 2 di quel item
Sarà un item crafting per craftarsi cose come ali, skin, robe evento etc

**Comment by Celebi91** [comment]
Ah te li deve dare insieme al bix insomma... ok

Il Lun 16 Set 2019, 19:50 Achille88 <notifications@github.com> ha scritto:

**Comment by Achille-exe** [comment]
Esatto, grazie

**Comment by Celebi91** [comment]
done
