### ISSUE TITLE
Set up Elitepvpers and Inforge NosChaos Presentation

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#17]
Need to set up a little presentation of our server with some basic information and screens

**Comment by Celebi91** [comment]
Lo faccio più tardi.

**Comment by Achille-exe** [comment]
Done https://www.elitepvpers.com/forum/nostale-pserver-advertising/4664258-noschaos-full-pvp-act-4-server-new-mastery-system.html
