### ISSUE TITLE
New Maestry System 

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#19]
New maestry system, all players will have 3 choices to do after choosing their class.
They can decide to have:
(FIRST CHOICE) 1. More attack 2. More Defence 3. More Speed 
(SECOND CHOICE) 1. More attack 2. More Defence 3. More Elusion 
(THIRD CHOICE) 1. One permanent Buff(attack) 2. One permanent Buff (element) 3. One permanent buff (elusion) 

The maestry MUST be one for Choice, no more than one so each player can build his character having 3 total improvements (3 buff)

And then they will build their own character with the Hero Books and Calvin/Krem Skills (REWORKED)

**Comment by Achille-exe** [comment]
The buffs and the Attack/defence/speed/elusion need to be tested first
I'll send here all the buff for each maestry

**Comment by Achille-exe** [comment]
Prima Maestria:                                              Buff ID:
●  +15% Attacco                                                   492
●  +15% Difesa                                                      493
● +15% HP/MP                                                    494

Seconda Maestria:
● +5% Danno e Difesa                                        242
● +3% Attacco e Difesa PvP                             491
●  +1 Velocità                                                          28

Terza Maestria:
● +500 Difesa Ravv. e Distante + 1 Lvl Dif     680
● +10% Attacco e Difesa PvP                            673
● +2 Velocità                                                            29

N.B. Può essere scelto 1 buff per maestria (SOLO UNO) per il resto del gioco nel PG

**Comment by Achille-exe** [comment]
Maestry file 

https://www.zamzar.com/uploadComplete.php?convertFile=7z&to=zip&session=bb6adc827dc655a295e9f8cde9dbb8cd&email=false&tcs=Z75

Download this and put into your NosData Folder to active the Maestry

**Comment by Celebi91** [comment]
Done

**Comment by Celebi91** [comment]
done
