### ISSUE TITLE
New Costume NPC by Tendy

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#24]
1. 4177, 4179
2. 4181, 4185
3. 4183, 4187
4. 4231, 4237
5. 4232, 4238
6. 4233, 4239
7. 4365, 4367
8. 4382, 4384 
9. 4390, 4392
10. 4394, 4396
11. 4439, 4441
12. 4409 4411

**Comment by Celebi91** [comment]
Close
