### ISSUE TITLE
Creating 2 raids: LAURENA and FAFNIR

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#26]
FAFNIR:
This raid will only give you wings, fullmoon, gold, HERO BOOKS (All of them) and with very very low percentage the Onyx and Wind wings (This raid will be so difficult, only with a full team of 12/15 you will succeed)

LAURENA:
This raid will give you Crafting item for Special items (no changeable), wings, fullmoon, gold, box with perfections

**Comment by Achille-exe** [comment]
FAFNIR: 26

**Comment by Celebi91** [comment]
Done
