### ISSUE TITLE
Spawning item when you change class

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#27]
Warriors should spawn with these items:
Sword 4981
Crossbow 4978
Armor 4984

Archers should spawn with these items:
Bow 4983
Knife 4980
Armor 4986

Magicians should spawn with these items:
Staff 4982
Pistol 4979
Armor 4985

And all of them need to have in the inventory 25kk

**Comment by Celebi91** [comment]
done
