### ISSUE TITLE
Act.4 Coordinate (edit)

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#30]
Please fix the boat in Act.4

**Comment by Celebi91** [comment]
Non è un bug
Va solo cambiata coordinata!

Il Dom 15 Set 2019, 16:15 Achille88 <notifications@github.com> ha scritto:

**Comment by Achille-exe** [comment]
Ok cambio, editato

**Comment by Celebi91** [comment]
Done
