### ISSUE TITLE
UPGRADE SP AND EQUIP 

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#31]
When you upgrade your SP and your Equip the window disappears, change it please so the window won't disappear

**Comment by Celebi91** [comment]
Chiedo

**Comment by Achille-exe** [comment]
Grazie

**Comment by Celebi91** [comment]
Ha detto Sai, che è una merdata.

Il Lun 16 Set 2019, 19:42 Achille88 <notifications@github.com> ha scritto:

**Comment by Achille-exe** [comment]
Asd ma almeno non devono sempre ricliccare sempre, poi diventa palloso, lo dico perchè da fastidio tanto anche a me e poi per rarizzare/uppare ci si mette di media 20min a item di media quindi può essere una gran palla

**Comment by Celebi91** [comment]
done
