### ISSUE TITLE
Add item 1252 as Arena Winner Item

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#38]
When you double click on Item 1123 you will have Arena Winners WIngs for 1 month

**Comment by Tendy-Insane** [comment]
1252 will be better i think

**Comment by Achille-exe** [comment]
1252 written down

**Comment by Celebi91** [comment]
Future

Il Mar 17 Set 2019, 20:50 Tendy-Insane <notifications@github.com> ha
scritto:

**Comment by Celebi91** [comment]
done
