### ISSUE TITLE
Add item 9636 for Family Lvl 20

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#39]
When you double-click on item 9636 your family will have lvl 20

**Comment by Celebi91** [comment]
Future

Il Mar 17 Set 2019, 20:48 Achille88 <notifications@github.com> ha scritto:

**Comment by Achille-exe** [comment]
This is for the ChaosMall shop

**Comment by Celebi91** [comment]
Ok domani li faccio

Il Mar 17 Set 2019, 20:48 Achille88 <notifications@github.com> ha scritto:

**Comment by Celebi91** [comment]
done
