### ISSUE TITLE
Bug Item Lvl. SP

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#41]
So if you buy a splvl1+13 from the job and equip (without pressing G) and use the Item Max SP your game will crash and when you log in your sp wiil have job 125 and you still have the obj

**Comment by Celebi91** [comment]
Mandare a Sai

Il Mar 17 Set 2019, 21:43 Achille88 <notifications@github.com> ha scritto:

**Comment by Celebi91** [comment]
fixx
