### ISSUE TITLE
Trade Bug

### ISSUE THREAD

**Issue by Tendy-Insane** [Achille-exe/NosChaos#47]
Players can't trade, when They put eq in trade get kick.

**Comment by Achille-exe** [comment]
Thank you for being active also in github bro

**Comment by Celebi91** [comment]
Done

**Comment by Tendy-Insane** [comment]
Still bugged :c

**Comment by Achille-exe** [comment]
THIS IS FOR UNBUG TRADE
[InventoryPacketHandler.zip](https://github.com/Achille88/NosChaos/files/3649332/InventoryPacketHandler.zip)
