### ISSUE TITLE
After 5 Min the server kick you out

### ISSUE THREAD

**Issue by Achille-exe** [Achille-exe/NosChaos#7]

**Comment by Celebi91** [comment]
This is a way to keep GM at bay. It's not a bug. I close.

**Comment by Achille-exe** [comment]
Also normal players has this issue, i re-open

**Comment by Achille-exe** [comment]
Also please put 20/30 minutes for kick

**Comment by Tendy-Insane** [comment]
User - DEV get kick after 5 min, only Administrator don't have dc

**Comment by Celebi91** [comment]
Ok. Controll

Il Mer 11 Set 2019, 22:14 Tendy-Insane <notifications@github.com> ha
scritto:

**Comment by Celebi91** [comment]
Fixed
